// Auto-generated by tools/gen_icons.py — do not edit by hand.
#ifndef DASH_ICONS_H
#define DASH_ICONS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_img_dsc_t icon_coolant;
extern const lv_img_dsc_t icon_oil;
extern const lv_img_dsc_t icon_turbo;
extern const lv_img_dsc_t icon_dpf;
extern const lv_img_dsc_t icon_glow;
extern const lv_img_dsc_t icon_battery;
extern const lv_img_dsc_t icon_clock;
extern const lv_img_dsc_t icon_road;
extern const lv_img_dsc_t icon_glow_sm;
extern const lv_img_dsc_t icon_clock_sm;
extern const lv_img_dsc_t icon_road_sm;
extern const lv_img_dsc_t icon_pressure_sm;

#ifdef __cplusplus
}
#endif

#endif // DASH_ICONS_H
